<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gamereview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.gamereview':
      return t('
        <h2>Game Review Module for Drupal.</h2>
      ');
  }
}
/**
 * Implements hook_theme().
 */
function gamereview_theme($existing, $type, $theme, $path) {
  $variables = array(
    'gamereview' => array(
      'variables' => array(
        'source_text' => NULL,
      ),
      'template' => 'gamereview',
    ),
  );
  return $variables;
}
